name: rijhub
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  firebase_core: ^3.9.0
  firebase_analytics: ^11.4.1
  firebase_messaging: ^15.2.1
  awesome_notifications: ^0.10.0
  auto_size_text: 3.0.0
  badges: ^3.1.2
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  carousel_slider: ^5.1.1
  collection: 1.19.1
  dropdown_button2: 2.3.9
  easy_debounce: ^2.0.3
  equatable: 2.0.7
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  flutter_rating_bar: 4.0.1
  flutter_svg: ^2.2.3
  font_awesome_flutter: ^10.9.1
  from_css_color: 2.0.0
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  http: ^1.6.0
  intl: 0.20.2
  json_path: ^0.8.0
  mime_type: ^1.0.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.19
  path_provider_foundation: ^2.4.2
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  provider: ^6.1.5+1
  shared_preferences: 2.5.3
  shared_preferences_android: ^2.4.13
  shared_preferences_foundation: 2.5.4
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.3
  shared_preferences_windows: 2.4.1
  sqflite: ^2.4.2
  sqflite_common: ^2.5.6
  timeago: 3.7.1
  universal_io: ^2.3.1
  url_launcher: ^6.3.2
  url_launcher_android: ^6.3.20
  url_launcher_ios: ^6.3.4
  url_launcher_linux: ^3.2.2
  url_launcher_macos: ^3.2.3
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.4.1
  url_launcher_windows: ^3.1.5
  xml: ^6.6.1
  webview_flutter: ^4.0.7
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^6.1.4
  crypto: ^3.0.3
  file_picker: ^10.3.7
  geolocator: ^14.0.2
  awesome_dialog: ^3.3.0
  cupertino_icons: ^1.0.0
  http_parser: any
  web_socket_channel: ^3.0.3
  socket_io_client: ^3.1.3

  # Map dependencies - migrated to Google Maps
  google_maps_flutter: ^2.4.0
  flutter_image_compress: ^2.4.0
  image_picker: ^0.8.7+5

dependency_overrides:
  # kept empty - avoid forcing older http/uuid versions which break packages
  # (if you intentionally need an override, re-add with care).

dev_dependencies:
  flutter_lints: ^6.0.0
  image: ^4.7.2
  lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: 'assets/icon/app_icon.png'
  adaptive_icon_background: '#ffffff'
  remove_alpha_ios: true
  adaptive_icon_foreground: 'assets/icon/app_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To reduce APK size we only include the essential assets explicitly.
  assets:
    # SSL CA
    - assets/ca/
    - assets/icon/
    - assets/fonts/
    - assets/images/
    # App logos used by UI
    - assets/images/logo_black.png
    - assets/images/logo_white.png
    # Background fade images (explicit files to avoid missing-variant checks)
    - assets/images/fade-1.webp
    - assets/images/fade-2.webp
    - assets/images/fade-3.webp
    - assets/images/fade-4.webp
    - assets/images/fade-5.webp
    # Carl image converted to WebP
    - assets/images/carl_1.webp
    - assets/images/carl_1.png
    # Nigeria states + LGAs JSON used by location fields
    - assets/jsons/nigeria_states_lgas.json

    # If you still need additional assets, add them explicitly here or
    # host large media remotely and load at runtime.

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
